update config and BE yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,6 +13,31 @@ commands:
               aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
               aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
               # exit 1
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here     
+      id: 
+        type: string
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          when: on_fail
+          command: |
+            echo "In revert-migrations"
+            ## Example: kvdb.io
+            # https://kvdb.io/Dw4F4ipUtypspF6ySi22x7/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            SUCCESS=$(curl -s --insecure https://kvdb.io/Dw4F4ipUtypspF6ySi22x7/migration_<< parameters.id >>)
+            echo $SUCCESS
+            ## Logic for reverting the database state
+            if [ $SUCCESS == 1 ];
+              then
+                cd backend
+                npm install
+                npm run migrations:revert
+                echo "Ran migration:revert"
+            fi  
 
 jobs:
   build-frontend:
@@ -185,7 +210,129 @@ jobs:
           root: ~/
           paths:
             - project/backend
-      - destroy-environment                   
+      - destroy-environment
+
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            sudo apt install -y tar gzip curl
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip -qq awscliv2.zip
+            sudo ./aws/install
+      - restore_cache:
+          keys: [backend-build]
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install 
+            npm run migrations >> migrations.txt      
+            cat migrations.txt  
+      - run:
+          name: Send migration results to kvdb
+          command: |
+            if grep -q "No migrations are pending" ~/project/backend/migrations.txt
+            then
+              echo "Successful migration"
+              # Using kvdb.io
+              curl --insecure https://kvdb.io/Dw4F4ipUtypspF6ySi22x7/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            else  
+              echo "Migration not necessary or not successful"
+              # Using kvdb.io
+              curl --insecure https://kvdb.io/Dw4F4ipUtypspF6ySi22x7/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
+            fi
+
+            # if grep -q "success" ~/project/backend/migrations.txt
+            # then
+            #   curl --insecure https://kvdb.io/Dw4F4ipUtypspF6ySi22x7/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
+            # fi
+            # exit 1
+      # - save_cache:
+      #     paths: [backend/node_modules]
+      #     key: backend-build
+     # Here's where you will add some code to rollback on failure      
+      - destroy-environment
+
+  deploy-frontend:
+    docker:
+     - image: circleci/node:13.8.0
+       user: root
+    steps:
+      - checkout
+      # - run:
+      #     name: install aws aws-cli
+      #     command: |
+      #       npm install -g aws-cli
+      #       aws configure list
+      - run:
+          name: "Install-dependencies"
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - run:
+          name: "Get-backend-url"
+          command: |
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: "Deploy-frontend-objects"
+          command: |
+            # your code here
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - destroy-environment
+      - revert-migrations:
+          id: ${CIRCLE_WORKFLOW_ID:0:7} 
+
+  deploy-backend:
+    docker:
+      - image: python:3.7-alpine3.16
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - '05:23:de:9b:17:72:1e:9b:cf:0b:47:e5:fd:17:ff:15'
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible
+      - restore_cache:
+          keys: [backend-build]
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Deploy backend
+          no_output_timeout: 30m
+          command: |
+            cd backend
+            npm install
+            npm run start 
+            npm run build
+            cd ..
+            tar -C backend -czvf artifact.tar.gz .
+            mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
+            mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
+            cd .circleci/ansible
+            echo "Contents of the inventory.txt file is ------$(cat inventory.txt)"
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - destroy-environment
+      - revert-migrations:
+          id: ${CIRCLE_WORKFLOW_ID:0:7}                   
 workflows:
   default:
     jobs:
@@ -206,3 +353,9 @@ workflows:
               only: [main]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
